version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: airflow_postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: airflow_redis
    ports:
      - "6379:6379"

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: airflow_mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      - ../src:/opt/airflow/src
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "YourStrong@Passw0rd" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
      bash -c '
        /opt/mssql/bin/sqlservr &
        sleep 30
        echo "Iniciando execução do script SQL..."
        sqlcmd -S localhost -U sa -P "$$SA_PASSWORD" -i /opt/airflow/src/sql/init.sql
        wait
      '

  airflow-init:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    container_name: airflow_init
    depends_on:
      - postgres
      - redis
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres/airflow
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CORE__FERNET_KEY=k9Pn2HkGZqXsqbmr0nfzpwZkUgn1_6ZX6_LYoKmB1RM=
      - AIRFLOW__WEBSERVER__SECRET_KEY=TztlEQ4-QO1wD5l_pRliH8Hy4pYm4ZXF6_LYoKmB1RM=
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__LOGGING__LOGGING_LEVEL=INFO
      - AIRFLOW__LOGGING__WORKER_LOG_SERVER_PORT=8793
      - AIRFLOW__CELERY__WORKER_LOG_SERVER_PORT=8793
      - PYTHONPATH=/opt/airflow/src
    volumes:
      - ../src:/opt/airflow/src
    entrypoint: 
      - /bin/bash
      - -c
      - |
        airflow db init && \
        airflow users create \
          --username airflow \
          --firstname airflow \
          --lastname admin \
          --role Admin \
          --email admin@airflow.com \
          --password airflow123
    restart: "no"

  airflow-webserver:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    container_name: airflow_webserver
    depends_on:
      - airflow-init
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres/airflow
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CORE__FERNET_KEY=k9Pn2HkGZqXsqbmr0nfzpwZkUgn1_6ZX6_LYoKmB1RM=
      - AIRFLOW__WEBSERVER__SECRET_KEY=TztlEQ4-QO1wD5l_pRliH8Hy4pYm4ZXF6_LYoKmB1RM=
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/src/dags
      - AIRFLOW__LOGGING__LOGGING_LEVEL=INFO
      - AIRFLOW__LOGGING__WORKER_LOG_SERVER_PORT=8793
      - AIRFLOW__CELERY__WORKER_LOG_SERVER_PORT=8793
      - PYTHONPATH=/opt/airflow/src
      - SQL_SERVER=mssql
      - SQL_DATABASE=ANTAQ
      - SQL_USERNAME=vinia6
      - SQL_PASSWORD=12345
    volumes:
      - ../src:/opt/airflow/src
      - ../data:/opt/airflow/data
      - /dev/shm:/dev/shm
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    container_name: airflow_scheduler
    depends_on:
      - airflow-init
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres/airflow
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CORE__FERNET_KEY=k9Pn2HkGZqXsqbmr0nfzpwZkUgn1_6ZX6_LYoKmB1RM=
      - AIRFLOW__WEBSERVER__SECRET_KEY=TztlEQ4-QO1wD5l_pRliH8Hy4pYm4ZXF6_LYoKmB1RM=
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/src/dags
      - AIRFLOW__LOGGING__LOGGING_LEVEL=INFO
      - AIRFLOW__LOGGING__WORKER_LOG_SERVER_PORT=8793
      - AIRFLOW__CELERY__WORKER_LOG_SERVER_PORT=8793
      - PYTHONPATH=/opt/airflow/src
    volumes:
      - ../src:/opt/airflow/src
      - ../data:/opt/airflow/data
    command: scheduler

  airflow-worker:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    container_name: airflow_worker
    depends_on:
      - airflow-init
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres/airflow
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CORE__FERNET_KEY=k9Pn2HkGZqXsqbmr0nfzpwZkUgn1_6ZX6_LYoKmB1RM=
      - AIRFLOW__WEBSERVER__SECRET_KEY=TztlEQ4-QO1wD5l_pRliH8Hy4pYm4ZXF6_LYoKmB1RM=
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/src/dags
      - AIRFLOW__LOGGING__LOGGING_LEVEL=INFO
      - AIRFLOW__LOGGING__WORKER_LOG_SERVER_PORT=8793
      - AIRFLOW__CELERY__WORKER_LOG_SERVER_PORT=8793
      - PYTHONPATH=/opt/airflow/src
    volumes:
      - ../src:/opt/airflow/src
      - ../data:/opt/airflow/data
    command: celery worker

volumes:
  postgres_data:
  mssql_data:
